### ISSUE TITLE
Your informations

### ISSUE THREAD

**Issue by yassbeno** [AyanUpadhaya/mailsender#1]
Is that your mail + password in the code ? if so be careful 🤔 
if not, good !

**Comment by AyanUpadhaya** [comment]
Thank you for contacting me. Of course not. I will never put my credentials
as public. In the creds file it is empty. Thats for if some one might wants
to use it.

**Comment by AyanUpadhaya** [comment]
> Is that your mail + password in the code ? if so be careful 🤔 if not, good !

yassbeno thank you bringing this to attention. it happened because it was one of my oldest project and at that time I was new to git and forgot to edit. Although the password doesn't work anymore because few moths ago I changed it and I also have some further security activated with my account. Credentials has been removed.
